### ISSUE TITLE
R script tcc2bootstrap2.R does not exist

### ISSUE THREAD

**Issue by winni2k** [pachterlab/aggregationDE#1]
The script referenced at https://github.com/pachterlab/aggregationDE/blob/master/R/Snakefile#L77 does not appear to exist in this repository.  Can you point me to a location where I can download it from?

**Comment by winni2k** [comment]
If I try and use [tcc2bootstrap.R](https://github.com/pachterlab/aggregationDE/blob/master/R/tcc2bootstrap.R) instead, then I get an error about `matrix.tsv` not existing.  I think `kallisto pseudo` outputs to `pseudoalignments.tsv` instead.

However, if I edit `tcc2bootstrap.R` to use `pseudoalignments.tsv` then I get this warning:
```
In matrix(tccs, nrow = 7) :
  data length [5626] is not a sub-multiple or multiple of the number of rows [7]
[1]   6 804
[1] "ncells, ntccs"
[1] 6
[1] 804
[1] "creating file"
[1] "wd/tcc_bootstrap/A5_S5_L001/1/abundance.h5"
```

Is that a problem?

My `pseudoalignments.tsv` file only contains two columns and no header.

**Comment by winni2k** [comment]
Finally, `tcc2bootstrap.R` dies with the error:
```
Error in H5Fcreate(file) : HDF5. File accessability. Unable to open file.
Calls: sapply ... FUN -> write_h5 -> h5createFile -> H5Fcreate -> .Call
Execution halted
```
It looks like some subdirectories are not being created.

**Comment by winni2k** [comment]
Is it safe to use `tcc2bootstrap.R` instead of `tcc2bootstrap2.R` to perform a gene-level differential analysis at transcript level?

**Comment by lynnyi** [comment]
Hi @winni2k,

Thanks for your question and apologies for the inconvenience. Your error is a result of the formatting change to pseudoalignments.tsv in the most recent update to kallisto, which no longer outputs a matrix.tsv.

If you would like to perform gene-analysis at the transcript level, we are implementing this functionality in sleuth. It is currently available on the 'devel' branch of sleuth (https://github.com/pachterlab/sleuth/tree/devel) and we will be releasing it shortly with a vignette (draft of vignette here: https://github.com/pachterlab/sleuth_walkthroughs/blob/pval_agg/pval_agg/analysis.html -- you can download as a html and open with a browser for readability).  It would be great for us if you decide to test our devel version of sleuth and the vignette.

Alternatively if you would like to continue with the code in this repo, what you can do is to convert your pseudoalignments.tsv into a full matrix (dimension # cells to #TCCs), and use the write_h5 function from tcc2bootstrap on each row (i.e. each cell) to write the bootstraps to h5 file that is readable by sleuth, and then continue with the snakemake pipeline.

Let me know if you have any other questions.

Best,
Lynn

**Comment by winni2k** [comment]
Hi Lynn,
I am happy to try out the implementation in sleuth.  Thanks for the thorough response!

Regards,
Winni
